//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control_Task_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class postcard
    {
        public int id_postcard { get; set; }
        public Nullable<int> id_sender { get; set; }
        public Nullable<int> id_recipient { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual recipient recipient { get; set; }
        public virtual sender sender { get; set; }
    }
}
